### ISSUE TITLE
Booster backend crashes

### ISSUE THREAD

**Issue by spencerhaoxiao** [runtimeverification/hs-backend-booster#410]
The latest kontrol version 0.1.83 which uses K version 6.1.41 crashes when prove the [optimism code](https://github.com/runtimeverification/_audits_Ethereum-optimism_pausability/tree/cheatcode-setup/packages/contracts-bedrock) by running the command `cat verify | sh` under the folder [packages/contracts-bedrock](https://github.com/runtimeverification/_audits_Ethereum-optimism_pausability/tree/cheatcode-setup/packages/contracts-bedrock) with the following message:

```
+ kontrol prove --max-depth 10000 --max-iterations 10000 --smt-timeout 100000 --bmc-depth 10 --workers 2 --bug-report SetupBugReport --no-break-on-calls --auto-abstract-gas --match-test StateDiffTest.testVerifyStateChange --use-booster
Bug report exists, removing: SetupBugReport.tar
Running functions: ['StateDiffTest.testVerifyStateChange()']
[Info#proxy] Loading definition from kout/kompiled/definition.kore, main module "FOUNDRY-MAIN"
[Info#kore] : Info (LogMessage):
    Reading the input file TimeSpec {sec = 0, nsec = 92346000} []
[Info#kore] : Info (LogMessage):
    Parsing the file TimeSpec {sec = 0, nsec = 0} []
[Info#kore] : Info (LogMessage):
    Verifying the definition TimeSpec {sec = 0, nsec = 0} []
[Info#kore] : Info (LogMessage):
    Executing TimeSpec {sec = 1, nsec = 711169000} []
[Info#kore] : Info (LogMessage):
    Reading the input file TimeSpec {sec = 0, nsec = 88867000} []
[Info#kore] : Info (LogMessage):
    Parsing the file TimeSpec {sec = 0, nsec = 0} []
[Info#kore] : Info (LogMessage):
    Verifying the definition TimeSpec {sec = 0, nsec = 0} []
Created bug report: kore-rpc-booster.tar.gz
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/62v1l08gxi6rlrgagb6wp6sljx1kvwrn-python3.10-multiprocess-0.70.15/lib/python3.10/site-packages/multiprocess/pool.py", line 579, in _handle_results
    task = get()
  File "/nix/store/62v1l08gxi6rlrgagb6wp6sljx1kvwrn-python3.10-multiprocess-0.70.15/lib/python3.10/site-packages/multiprocess/connection.py", line 254, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/nix/store/6ajmbp51laiswl6nsi52n4wbgqsi0508-python3.10-dill-0.3.7/lib/python3.10/site-packages/dill/_dill.py", line 301, in loads
    return load(file, ignore, **kwds)
  File "/nix/store/6ajmbp51laiswl6nsi52n4wbgqsi0508-python3.10-dill-0.3.7/lib/python3.10/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/nix/store/6ajmbp51laiswl6nsi52n4wbgqsi0508-python3.10-dill-0.3.7/lib/python3.10/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
TypeError: NoSuchProcess.__init__() missing 1 required positional argument: 'pid'
```

The bug report is attached [kore-rpc-booster.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/13582730/kore-rpc-booster.tar.gz)

**Comment by spencerhaoxiao** [comment]
Close this because this is caused by a reinstalling of kontrol without cleaning and regenerating the kout file.
