### ISSUE TITLE
Backend update causes crash when falling back to old backend

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/hs-backend-booster#451]
Attached is a bug report for a failing proof on the update deps PR: https://github.com/runtimeverification/evm-semantics/pull/2236

Instead, we get an error which seems to appear to becoming from sending a given term to the old backend:

```
INFO 2024-01-09 23:10:16,107 pyk.utils - Added file to bug report failing-kevm.tar:commands/010.sh: /tmp/tmp9jcksez3
[Info] Process request 6 execute
[Info#proxy] Starting execute request
[Info#proxy] Booster Aborted at Depth {getNat = 20}
[Info#proxy] Simplifying booster state and falling back to Kore
[Info#proxy] Simplifying execution state
[Info#booster] Simplifying a pattern
[Warn#proxy] Unexpected failure when calling Kore simplifier, returning original term
INFO 2024-01-09 23:10:16,387 pyk.utils - Added file to bug report failing-kevm.tar:rpc_3a0b47780d60687968fb8e6d11d8b1f76d24e73f861ec35b43d2dd8de0b81935/006_response.json: /tmp/tmp5avr61e0
INFO 2024-01-09 23:10:16,476 pyk.utils - Added file to bug report failing-kevm.tar:commands/011.sh: /tmp/tmpl597muqu
ERROR 2024-01-09 23:10:16,476 kevm_pyk.utils - Proof crashed: 3a0b47780d60687968fb8e6d11d8b1f76d24e73f861ec35b43d2dd8de0b81935
Could not verify pattern
Traceback (most recent call last):
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 784, in _request
    return self._client.request(method, **params)
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 247, in request
    return self._default_client.request(method, **params)
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 326, in request
    self._check(data)
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 338, in _check
    raise JsonRpcError(**response['error'])
pyk.kore.rpc.JsonRpcError: Could not verify pattern

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/src/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 117, in run_prover
    prover.advance_proof(
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/proof/reachability.py", line 752, in advance_proof
    self.advance_pending_node(
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/proof/reachability.py", line 716, in advance_pending_node
    self.kcfg_explore.extend(
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 371, in extend
    extend_result = self.extend_cterm(
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 414, in extend_cterm
    cterm, next_cterms, depth, vacuous, next_node_logs = self.cterm_execute(
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 91, in cterm_execute
    response = self._kore_client.execute(
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 824, in execute
    result = self._request('execute', **params)
  File "/home/dev/.cache/pypoetry/virtualenvs/kevm-pyk-kMaowF10-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 787, in _request
    raise KoreClientError(message=err.message, code=err.code, data=err.data) from err
pyk.kore.rpc.KoreClientError: Could not verify pattern
INFO 2024-01-09 23:10:16,477 kevm_pyk.__main__ - Proof timing 3a0b47780d60687968fb8e6d11d8b1f76d24e73f861ec35b43d2dd8de0b81935: 3.8293566703796387s
[Info#proxy] Server shutting down
INFO 2024-01-09 23:10:16,566 pyk.kore.rpc - KoreServer stopped: 0.0.0.0:36111, pid=2647727
PROOF FAILED: 3a0b47780d60687968fb8e6d11d8b1f76d24e73f861ec35b43d2dd8de0b81935
```

[failing-kevm.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/13881053/failing-kevm.tar.gz)

**Comment by jberthold** [comment]
The actual error is `"error":"Expecting sort SortGas{} but got SortInt{}."`. 
This is most likely caused by the new `rawTerm` unwrapping of simplified concrete terms in booster. Note that `SortInt` is a subsort of `SortGas`. A `rawTerm(inj{S, SortKItem{}}(X))` is unwrapped to just X. If before returning the value, a chain of injections is shortened, like `inj{SortGas,SortKItem}(inj{SortInt, SortGas}(X))` simplifying to `inj{SortInt, SortKItem}(X)` then we will get the raw `X` where an injection into `SortGas `would be required.
#449 appears related.
